#*****************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# RAS_project.tcl: Tcl script for re-creating project 'RAS_project_simu'
#
# Generated by Vivado on Wed Jun 23 09:34:28 +0200 2021
# IP Build 2902112 on Wed May 27 22:43:36 MDT 2020
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (RAS_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/RAS_project_simu/RAS_project_simu.srcs/sources_1/new/mux_overlap_neg.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/RAS_project_simu/RAS_project_simu.srcs/sources_1/new/mux_overlap_pos.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/RAS_project_simu/RAS_project_simu.srcs/sources_1/new/shift_register_15b.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/RAS_project_simu/RAS_project_simu.srcs/sources_1/new/mux_overlap.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/RAS_project_simu/RAS_project_simu.srcs/sim_1/new/row_addressing_tb.vhd"
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_ok/okCoreHarness.v"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_ok/okLibrary.v"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_ok/okPipeIn.v"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_ok/okPipeOut.v"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_ok/okTriggerIn.v"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_ok/okTriggerOut.v"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/FAS_package.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/div_freq.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/div_freq2.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/mux_overlap.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/mux_overlap_neg.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/mux_overlap_pos.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_sim/okLibrary_sim.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/read_5MHz.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/sequence_treatment.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/shift_register_15b.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/row_addressing.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/Script/FAS_package.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/Script/div_freq2.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_sim/mappings.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/okLibrary_sim.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/Script/row_addressing.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/Script/sequence_treatment.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/Script/div_freq.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/Script/mux_overlap.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/Script/mux_overlap_neg.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/Script/mux_overlap_pos.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/Script/read_5MHz.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/Script/shift_register_15b.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_sim/parameters.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_sim/okPipeIn.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_sim/okHost.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_sim/okPipeOut.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_sim/okWireOR.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75/okCoreHarness.v"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75/okLibrary.v"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75/okPipeIn.v"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75/okPipeOut.v"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75/okTriggerIn.v"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75/okWireIn.v"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/mappings.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/parameters.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/okPipeOut.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/okPipeIn.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/okTriggerIn.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/okWireIn.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/okWireOR.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/okHost.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/ip/fifo_pipeout/fifo_pipeout.xci"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/ip/fifo_pipein/fifo_pipein.xci"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/ip/fifoHK_pipeout/fifoHK_pipeout.xci"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/constraints/xem7310.xdc"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_sim/okTriggerIn.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/XEM7310-A75_sim/okTriggerOut.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/simu/tb/row_addressing_tb.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/sim/tb/row_addressing_tb.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/Simulation/row_addressing_tb.vhd"
#    "C:/Users/ATHENA_X-IFU/Documents/Noemie2020/solution_commande/ras-a75-fw/src/row_addressing_tb.vhd"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "RAS_project_simu"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "RAS_project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/RAS_project_simu"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a75tfgg484-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7a75tfgg484-1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "2" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "2" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "2" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "2" -objects $obj
set_property -name "webtalk.questa_launch_sim" -value "3" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "2" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "2" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "2" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "457" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/src/XEM7310-A75_ok/okCoreHarness.v"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_ok/okLibrary.v"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_ok/okPipeIn.v"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_ok/okPipeOut.v"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_ok/okTriggerIn.v"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_ok/okTriggerOut.v"] \
 [file normalize "${origin_dir}/src/FAS_package.vhd"] \
 [file normalize "${origin_dir}/src/div_freq.vhd"] \
 [file normalize "${origin_dir}/src/div_freq2.vhd"] \
 [file normalize "${origin_dir}/src/mux_overlap.vhd"] \
 [file normalize "${origin_dir}/src/mux_overlap_neg.vhd"] \
 [file normalize "${origin_dir}/src/mux_overlap_pos.vhd"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_sim/okLibrary_sim.vhd"] \
 [file normalize "${origin_dir}/src/read_5MHz.vhd"] \
 [file normalize "${origin_dir}/src/sequence_treatment.vhd"] \
 [file normalize "${origin_dir}/src/shift_register_15b.vhd"] \
 [file normalize "${origin_dir}/src/row_addressing.vhd"] \
 [file normalize "${origin_dir}/src/Script/FAS_package.vhd"] \
 [file normalize "${origin_dir}/src/Script/div_freq2.vhd"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_sim/mappings.vhd"] \
 [file normalize "${origin_dir}/src/okLibrary_sim.vhd"] \
 [file normalize "${origin_dir}/src/Script/row_addressing.vhd"] \
 [file normalize "${origin_dir}/src/Script/sequence_treatment.vhd"] \
 [file normalize "${origin_dir}/src/Script/div_freq.vhd"] \
 [file normalize "${origin_dir}/src/Script/mux_overlap.vhd"] \
 [file normalize "${origin_dir}/src/Script/mux_overlap_neg.vhd"] \
 [file normalize "${origin_dir}/src/Script/mux_overlap_pos.vhd"] \
 [file normalize "${origin_dir}/src/Script/read_5MHz.vhd"] \
 [file normalize "${origin_dir}/src/Script/shift_register_15b.vhd"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_sim/parameters.vhd"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_sim/okPipeIn.vhd"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_sim/okHost.vhd"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_sim/okPipeOut.vhd"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_sim/okWireOR.vhd"] \
 [file normalize "${origin_dir}/src/XEM7310-A75/okCoreHarness.v"] \
 [file normalize "${origin_dir}/src/XEM7310-A75/okLibrary.v"] \
 [file normalize "${origin_dir}/src/XEM7310-A75/okPipeIn.v"] \
 [file normalize "${origin_dir}/src/XEM7310-A75/okPipeOut.v"] \
 [file normalize "${origin_dir}/src/XEM7310-A75/okTriggerIn.v"] \
 [file normalize "${origin_dir}/src/XEM7310-A75/okWireIn.v"] \
 [file normalize "${origin_dir}/src/mappings.vhd"] \
 [file normalize "${origin_dir}/src/parameters.vhd"] \
 [file normalize "${origin_dir}/src/okPipeOut.vhd"] \
 [file normalize "${origin_dir}/src/okPipeIn.vhd"] \
 [file normalize "${origin_dir}/src/okTriggerIn.vhd"] \
 [file normalize "${origin_dir}/src/okWireIn.vhd"] \
 [file normalize "${origin_dir}/src/okWireOR.vhd"] \
 [file normalize "${origin_dir}/src/okHost.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/RAS_project_simu/RAS_project_simu.srcs/sources_1/new/mux_overlap_neg.vhd" ]\
 [file normalize "${origin_dir}/RAS_project_simu/RAS_project_simu.srcs/sources_1/new/mux_overlap_pos.vhd" ]\
 [file normalize "${origin_dir}/RAS_project_simu/RAS_project_simu.srcs/sources_1/new/shift_register_15b.vhd" ]\
 [file normalize "${origin_dir}/RAS_project_simu/RAS_project_simu.srcs/sources_1/new/mux_overlap.vhd" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/src/XEM7310-A75_ok/okCoreHarness.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_ok/okLibrary.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_ok/okPipeIn.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_ok/okPipeOut.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_ok/okTriggerIn.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_ok/okTriggerOut.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/src/FAS_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/div_freq.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/div_freq2.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/mux_overlap.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/mux_overlap_neg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/mux_overlap_pos.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_sim/okLibrary_sim.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/read_5MHz.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/sequence_treatment.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/shift_register_15b.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/row_addressing.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/Script/FAS_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/Script/div_freq2.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_sim/mappings.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/okLibrary_sim.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/Script/row_addressing.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/Script/sequence_treatment.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/Script/div_freq.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/Script/mux_overlap.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/Script/mux_overlap_neg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/Script/mux_overlap_pos.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/Script/read_5MHz.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/Script/shift_register_15b.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_sim/parameters.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_sim/okPipeIn.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_sim/okHost.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_sim/okPipeOut.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_sim/okWireOR.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75/okCoreHarness.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75/okLibrary.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75/okPipeIn.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75/okPipeOut.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75/okTriggerIn.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75/okWireIn.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/src/mappings.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/parameters.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/okPipeOut.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/src/okPipeIn.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/src/okTriggerIn.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/src/okWireIn.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/src/okWireOR.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/src/okHost.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
set file "new/mux_overlap_neg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/mux_overlap_pos.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/shift_register_15b.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/mux_overlap.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "row_addressing" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/fifo_pipeout/fifo_pipeout.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/fifo_pipeout/fifo_pipeout.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/fifo_pipein/fifo_pipein.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/fifo_pipein/fifo_pipein.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/fifoHK_pipeout/fifoHK_pipeout.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/fifoHK_pipeout/fifoHK_pipeout.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constraints/xem7310.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constraints/xem7310.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/constraints/xem7310.xdc"]" -objects $obj
set_property -name "target_part" -value "xc7a75tfgg484-1" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$origin_dir/constraints/xem7310.xdc"]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${origin_dir}/src/XEM7310-A75_sim/okTriggerIn.vhd"] \
 [file normalize "${origin_dir}/src/XEM7310-A75_sim/okTriggerOut.vhd"] \
 [file normalize "${origin_dir}/simu/tb/row_addressing_tb.vhd"] \
 [file normalize "${origin_dir}/sim/tb/row_addressing_tb.vhd"] \
 [file normalize "${origin_dir}/src/Simulation/row_addressing_tb.vhd"] \
 [file normalize "${origin_dir}/src/row_addressing_tb.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/RAS_project_simu/RAS_project_simu.srcs/sim_1/new/row_addressing_tb.vhd" ]\
]
set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/src/XEM7310-A75_sim/okTriggerIn.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/src/XEM7310-A75_sim/okTriggerOut.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/simu/tb/row_addressing_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/sim/tb/row_addressing_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/Simulation/row_addressing_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/row_addressing_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
set file "new/row_addressing_tb.vhd"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "nl.mode" -value "funcsim" -objects $obj
set_property -name "top" -value "row_addressing_tb" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "50000ns" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a75tfgg484-1 -flow {Vivado Synthesis 2020} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2020" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7a75tfgg484-1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a75tfgg484-1 -flow {Vivado Implementation 2020} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2020" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7a75tfgg484-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
