# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/paulm/OneDrive/Bureau/ras-a75-fw-1.3.0/ras-a75-fw-1.3.0/constraints/xem7310.xdc

# IP: C:/Users/paulm/OneDrive/Bureau/ras-a75-fw-1.3.0/ras-a75-fw-1.3.0/ip/fifoHK_pipeout/fifoHK_pipeout.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifoHK_pipeout || ORIG_REF_NAME==fifoHK_pipeout} -quiet] -quiet

# IP: C:/Users/paulm/OneDrive/Bureau/ras-a75-fw-1.3.0/ras-a75-fw-1.3.0/ip/fifo_pipeout/fifo_pipeout.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_pipeout || ORIG_REF_NAME==fifo_pipeout} -quiet] -quiet

# IP: C:/Users/paulm/OneDrive/Bureau/ras-a75-fw-1.3.0/ras-a75-fw-1.3.0/ip/fifo_pipein/fifo_pipein.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_pipein || ORIG_REF_NAME==fifo_pipein} -quiet] -quiet
